# pull official base image
FROM python:3.9-slim-buster

# maintainers info
LABEL maintainer="bigdeli.ali3@gmail.com"

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
COPY ./requirements.dev.txt ./requirements.txt
RUN pip install --upgrade pip --index=https://mirrors.aliyun.com/pypi/simple/ && pip install -r requirements.txt --index=https://mirrors.aliyun.com/pypi/simple/

# copy project
COPY ./core .